# This is a basic workflow to help you get started with Actions

name: Build Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14.18.3'

      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: npm install
        
      - name: Build Release
        run: npm run pkg

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          draft: false
          prerelease: false

      - name: Upload Release Windows Asset
        id: upload-release-window-asset
        uses: actions/upload-release-asset@master
        env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./dist/oimi-live-win.exe
         asset_name:  oimi-live.exe
         asset_content_type: application/x-ms-dos-executable
 
      - name: Upload Release Linux Asset
        id: upload-release-linux-asset
        uses: actions/upload-release-asset@master
        env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./dist/oimi-live-linux
         asset_name:  oimi-live-linux
         asset_content_type: application/binary
      
      - name: Upload Release MACOS Asset
        id: upload-release-mac-asset
        uses: actions/upload-release-asset@master
        env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./dist/oimi-live-macos
         asset_name:  oimi-live-macos
         asset_content_type: application/binary

      
